#!/bin/sh
set -eu

cd "$(dirname "$(realpath -- "$0")")"

version=0.1

espa -vkp ru A1_PrimaryNeeds_V1.esp.yaml || exit 1
touch -t 200402131853 A1_PrimaryNeeds_V1.esp
#iconv -f UTF-8 -t CP1251 README | perl -p -e 's/\n/\r\n/' > Readme.txt || exit 1
#iconv -f UTF-8 -t CP1251 VERSIONS | perl -p -e 's/\n/\r\n/' > Versions.txt || exit 1
rm -rf A1_PrimaryNeeds_"$version"
rm -f A1_PrimaryNeeds_"$version".zip
mkdir A1_PrimaryNeeds_"$version" || exit 1
cp -a "Data Files" A1_PrimaryNeeds_"$version" || exit 1
#cp -a Screenshots Readme.txt Versions.txt A1_PrimaryNeeds_"$version" || exit 1
cp -a A1_PrimaryNeeds_V1.esp A1_PrimaryNeeds_"$version"/"Data Files" || exit 1
zip -v -X -9 -r A1_PrimaryNeeds_"$version".zip A1_PrimaryNeeds_"$version" || exit 1
